### ISSUE TITLE
AttributeError: type object 'Theme' has no attribute 'init_themes'

### ISSUE THREAD

**Issue by geiseri** [nyergler/hieroglyph#124] opened 2017-05-20 13:03 UTC
I see the following stacktrace with ``make slides``:

```
lib/python3.6/site-packages/hieroglyph/builder.py", line 50, in init_templates
    Theme.init_themes(self.confdir,
```

I am using:
* Python: 3.6.1
* Sphinx: 1.6.1
* Hiefoglyph: 0.7.1

**Comment by sanjioh** [comment] 2017-05-24 15:44
+1

confirmed here on
Python 3.5.3
Sphinx 1.6.1
Hieroglyph 0.7.1

**Comment by nyergler** [comment] 2017-05-24 17:03
Sphinx 1.6 made significant changes to the underlying theme handling, which
is probably the cause of this issue.

**Comment by Letme** [comment] 2017-06-06 12:04
+1 also have issue. Any timeframe on fix or should we dig in and provide a PR?

**Comment by nyergler** [comment] 2017-06-07 04:51
I don't have a timeframe for a fix; I'd love to review a PR :).

**Comment by bilderbuchi** [comment] 2017-07-24 09:19
So, apparently `init_themes()` was removed in commit https://github.com/sphinx-doc/sphinx/commit/faefe2b5a522763e918ae1ad67b02ae0bcde824f#diff-4feaa188ff5d39d95906200000776bcdL152 "Add HTMLThemeFactory class" by @tk0miya. 
This was part of PR https://github.com/sphinx-doc/sphinx/pull/3648 "Refactor sphinx.theming" and was merged into sphinx 1.6. The PR is not mentioned in the changelog, nor a mitigation/transition note about it. The only theme-related mention is 
> #3628: ``sphinx_themes`` entry_point is deprecated.  Please use ``sphinx.html_themes`` instead.
but I'm not sure if this is related/useful.

@tk0miya do you maybe have a pointer how to fix this?

**Comment by nyergler** [comment] 2017-09-06 16:45
This should be fixed with https://github.com/nyergler/hieroglyph/pull/129

**Closed by nyergler** 2017-09-06 16:45 UTC

**Comment by bilderbuchi** [comment] 2017-09-07 17:39
Thanks!
