### ISSUE TITLE
Sphinx 1.8 "Unknown node" traceback

### ISSUE THREAD

**Issue by oliver-sanders** [nyergler/hieroglyph#148] opened 2018-09-25 09:15 UTC
#### At sphinx 1.8 the slides builder is generating traceback on certain nodes:

Looks like an extension issue?

```
Exception occurred:
  File ".../sphinx/writers/html.py", line 897, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: graphviz
```

#### Minimal example to replicate

*conf.py*
```python
extensions = [
    'sphinx.ext.graphviz',
    'hieroglyph'
]

master_doc = 'index'
```

*index.rst*
```rst
Foo
===

.. digraph:: mygraph

   foo
```

Example compiles under sphinx 1.7.9

#### System Info

hieroglyph - 1.0.0  
Sphinx - 1.8.1   
Python - 2.7.15 / 3.6.6

**Comment by oliver-sanders** [comment] 2019-01-23 12:00
I can't work out a fix for this, I can, however, offer a dirty hack:

```diff
diff --git a/sphinx/writers/html.py b/sphinx/writers/html.py
index 454e7c4d2..82acce9e7 100644
--- a/sphinx/writers/html.py
+++ b/sphinx/writers/html.py
@@ -8,6 +8,8 @@
     :license: BSD, see LICENSE for details.
 """
 
+from sphinx.ext.graphviz import html_visit_graphviz
+
 import copy
 import os
 import posixpath
@@ -948,6 +950,8 @@ class HTMLTranslator(SphinxTranslator, BaseTranslator):
         # type: (nodes.Node) -> None
         raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
 
+    visit_graphviz = html_visit_graphviz
+
     # --------- METHODS FOR COMPATIBILITY --------------------------------------
 
     @property

```

Similar hacks will be required for other extensions which define their own `html_view_<extension>` methods.

This bodge doesn't work when applied to the `AbstractSlideBuilder` class (or any of its disciples), inheritance issues?

**Comment by oliver-sanders** [comment] 2019-01-23 12:22
Same dirty hack in the form of an extension:

```python
import sphinx

from sphinx.writers.html import HTMLTranslator
from sphinx.ext.graphviz import html_visit_graphviz

def setup(app):
    if tuple(int(x) for x in sphinx.__version__.split('.')) > (1, 7, 9):
        HTMLTranslator.visit_graphviz = html_visit_graphviz
```

**Comment by peircej** [comment] 2019-04-26 15:36
Sadly still a problem in Sphinx 2.0.1

**Comment by nyergler** [comment] 2019-07-31 13:42
Based on the hack here and patch in #156, I'm guessing this is due to the fact we're subclassing the HTML builder but not claiming to be `html`.

**Comment by nyergler** [comment] 2019-07-31 13:54
Actually, digging into the graphviz extension code, I guess the issue is that our builder isn't [registered for graphviz nodes](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/graphviz.py#L392). 

Perhaps the right solution would be to include registration for `slides` for builtin Sphinx extensions?

**Comment by oliver-sanders** [comment] 2019-07-31 16:05
I guess that wouldn't work for custom extensions though?

**Comment by nyergler** [comment] 2019-07-31 16:17
Correct. 

One other thing I'm not sure about is what effect making format `html` for the Slide Builder would be on the _real_ HTML builder; AFAIK builder names are supposed to be unique in Sphinx, so it wouldn't entirely surprise me if it busted HTML building. Should be relatively easy to test that.

**Comment by nyergler** [comment] 2019-07-31 16:22
Two more quick thoughts:

* #156 sets the format for the `AbstractSlideBuilder` to `html`; that property is overridden by the builders that are actually registered, so I'm not convinced it'll fix this issue.
* Setting `format = 'html'` on `SlideBuilder` and attempting to `make slides` in the `docs` directory results in the following error:

```
$ make slides
Running Sphinx v2.1.2

Extension error:
Builder 'html' already exists (in module sphinx.builders.html)
make: *** [slides] Error 2
```

So it appears that yes, builder formats _must_ be unique.

**Comment by lpirl** [comment] 2020-06-28 09:30
Unfortunately persists with
```
graphviz==0.14
hieroglyph==2.0.0
Sphinx==3.1.1
```

**Comment by nyergler** [comment] 2020-06-29 16:11
This should be fixed on `master` now; if you're able to test with `master`, @lpirl, that'd be much appreciated.

**Closed** 2020-06-29 16:10 UTC

**Comment by lpirl** [comment] 2020-06-30 18:40
Looks good @nyergler . Looking forward to the new release.

**Comment by nyergler** [comment] 2020-07-04 21:42
I just pushed Hieroglyph 2.1.0 to PyPI. Thanks for your help!
